### ISSUE TITLE
Is something wrong with jsonwebtoken 8.2.0

### ISSUE THREAD

**Issue by ashinzekene** [mikenicholson/passport-jwt#168]
I have had issues with authorization using this package. I was so frustrated I had to check the code and add logs. Here, I modified [extract_jwt.js](https://github.com/themikenicholson/passport-jwt/blob/master/lib/extract_jwt.js) to

```js
var jwt = require('jsonwebtoken');

module.exports  = function(token, secretOrKey, options, callback) {
    return jwt.verify(token, secretOrKey, options, (err, res) => {
        console.log(options.issuer);
        console.log(err.message, res)
        callback(err, res);
    });
};

``` 
I get this from the console

```
send_te_app
jwt issuer invalid. expected: send_te_app undefined
```
Is anyother person facing this issue

**Comment by mikenicholson** [comment]
Closing as this is not an issue with this package.
