### ISSUE TITLE
Working with jwt and flash messages

### ISSUE THREAD

**Issue by aryeharmon** [mikenicholson/passport-jwt#169]
Is it possible to work with JWT tokens and flash messages ([connect-flash](https://github.com/jaredhanson/connect-flash)) ? 

it seems flash messages are not saving in the session

**Comment by mikenicholson** [comment]
I'm not familiar with connect-flash.  If there is some bug with passport-jwt that is breaking connect-flash please provide a clear explanation and succinct example code.
