### ISSUE TITLE
Adding ES6 Defaults for AUTH_HEADER

### ISSUE THREAD

**Issue by JemiloII** [mikenicholson/passport-jwt#181]
https://github.com/mikenicholson/passport-jwt/blob/6b92631dfbde7143b9e046093dbf332107bce82e/lib/extract_jwt.js#L16

New to the project, but I thought this would be useful.
`extractors.fromHeader = function (header_name = AUTH_HEADER) {`

This way we could simply user `ExtractJWT.fromHeader()` without needing to type 'authorization'

**Comment by mikenicholson** [comment]
see `fromAuthHeader*` extractor functions. in [extract_jwt.js](https://github.com/mikenicholson/passport-jwt/blob/master/lib/extract_jwt.js)
