### ISSUE TITLE
Authorization header fallback logic

### ISSUE THREAD

**Issue by SaschaHeyer** [mikenicholson/passport-jwt#214]
Hi Folks,

is there any way to define a fallback to look for the authorization header.
**Sample**

- Check if the authorization header is preset in `x-forwarded-authorization`
- If not check if the authorization header is preset in `authorization`

We have services which might overwrite the header and set the initial header to `x-forwared-authorization`

![giphy](https://user-images.githubusercontent.com/1991664/86124722-dd340700-badb-11ea-97d6-fc49cde989a7.gif)

**Comment by SaschaHeyer** [comment]
I see this should be possible with `custom extractor function`

**Comment by mikenicholson** [comment]
> I see this should be possible with custom extractor function

Correct. Corner cases like this are why I moved reading the jwt from a request to extractor functions rather than trying to implement every possible permutation in the strategy.

Closing since no changes should be required.
