### ISSUE TITLE
Refresh_token

### ISSUE THREAD

**Issue by adamasantares** [mikenicholson/passport-jwt#223]
I don't see any information about refresh_token, I see access_token only. How should I get a new access token after it expired?

**Comment by shanutthankachan** [comment]
i think it will help you https://www.izertis.com/en/-/refresh-token-with-jwt-authentication-in-node-js

**Comment by qrhfz** [comment]
@shanutthankachan the refresh token list is stateful. it kinda misses the purpose of jwt. or am i missing something?

**Comment by mikenicholson** [comment]
This is out of the scope of this library.  Passport-jwt only decodes and validates access tokens. It does not handle refresh tokens.
