### ISSUE TITLE
vulnerability in passport-jwt's dependancy jsonwebtoken 

### ISSUE THREAD

**Issue by rprakash05** [mikenicholson/passport-jwt#244]
Updating to jsonwebtoken's latest version 9.0.0 resolves the vulnerability
Vulnerability details : https://github.com/advisories/GHSA-27h2-hvpr-p74q

**Comment by PetrShchukin** [comment]
Same here, using it with nest.js for JWT strategies, getting a high vulnerability.
![image](https://user-images.githubusercontent.com/46652336/209128087-1157b120-18b8-4b4f-9b9b-df5c82bb93bc.png)

**Comment by dfernandesbsolus** [comment]
We have the same problem!

**Comment by aperona-hai** [comment]
Went ahead and created https://github.com/mikenicholson/passport-jwt/pull/245

**Comment by Shereef** [comment]
@mikenicholson Please merge #245  and release ASAP Snyk is stopping our app from going to production with this version

Thank you!

**Comment by prince-kumar95** [comment]
I'm too facing this issues with snyk. @mikenicholson please let me know when will this be merged and released.
Thanks

**Comment by mikenicholson** [comment]
4.0.1 bumps the jsonwebtoken dependnecy and has been release to NPM

**Comment by Shereef** [comment]
Thanks so much !!
